### PR TITLE
stop editing /etc/sudoers directly

### PR DESCRIPTION
**Pull request by kjbweb**

### CODE REVIEW

**Comment by jeffreycoe** [comment]
Hi @kjbweb - If this is still an issue, would you be able to get this PR updated with the latest code, or can this PR be closed?

**Comment by kjbweb** [comment]
> Hi @kjbweb - If this is still an issue, would you be able to get this PR updated with the latest code, or can this PR be closed?

Hi @jeffreycoe, it is by the looks of things, I've updated my fork, hope it helps.

**Comment by jeffreycoe** [comment]
@kjbweb It looks like `lib/kitchen/driver/docker.rb` was modified or was accidentally added to your commit. Would you be able to remove this file from the change and then squash the commits? Once that's done, we should be able to merge. Thanks!

**Comment by joshuariojas** [comment]
@jeffreycoe The only made to `lib/kitchen/driver/docker.rb` are converting the line endings from Windows to Unix style. It was probably done by the submitter's local .gitconfig, but it does (appear to) bring that file in-line with the rest of the code base.

**Comment by jeffreycoe** [comment]
@joshuariojas Thanks Josh. I reviewed it as well and it looks to be fine. I'll merge this PR.

**Pull request merged**
