### PR TITLE
Add support for omnibus-caching

### PR DESCRIPTION
**Pull request by tduffield**
To save on time/bandwidth, store omnibus binaries in a named Docker Volume.

Signed-off-by: Tom Duffield <tom@chef.io>

### CODE REVIEW

**Comment by afiune** [comment]
Code looks fancy! Just add a few tests? 😄

**Comment by coderanger** [comment]
This is better handled via the layer system, see https://github.com/poise/poise-boiler/blob/master/lib/poise_boiler/helpers/kitchen/Dockerfile.erb#L82-L85 for an example.

**Comment by tduffield** [comment]
@coderanger Why is it better handled there?

**Comment by coderanger** [comment]
Because it's faster (doesn't re-run the install at all instead of just saving download time), is easier to prune, and can be shared by multiple test suites or cookbooks.

**Comment by tduffield** [comment]
@coderanger when using the chef provisioner, the install will be run regardless, would it not? There's nothing in here that short-circuits the provisioner as far as I can tell. The image build would perform the install, and then the provisioner would come in and perform the install again.

**Comment by coderanger** [comment]
@tduffield It does in fact skip the install :) https://github.com/test-kitchen/test-kitchen/blob/master/support/chef_base_install_command.sh#L221 (unless you request `require_chef_omnibus: latest` which always reinstalls for safety)

**Comment by tduffield** [comment]
@coderanger okay, i know this PR didn't reflect it, but what if we wanted to support abstract provisioner caching?

**Comment by coderanger** [comment]
Doesn't seem worthwhile enough to use a sub-par implementation for. Which was my whole point against the original PR :) If someone wants to have a fast, opinionated Docker setup using volumes then dokken is already great for that (and I generally recommend dokken over kitchen-docker to new users). `provision_command` supports any install command out there so it works fine with Ansible and Puppet too. Happy to take a doc change with examples for those if you know them off hand.

**Pull request closed without merging**
