### PR TITLE
Add ssh options when wait_for_ssh

### PR DESCRIPTION
**Pull request by devvesa**
Run a container prepared for upstart or systemd system management
daemons could take a little bit more to spawn and setup the ssh service.

This patch adds the :ssh_retries and :ssh_timeout driver configuration
options to be passed through the ssh client in wait_for_ssh function. I
based my patch in the current kitchen_ec2 driver:

https://github.com/test-kitchen/kitchen-ec2/blob/master/lib/kitchen/driver/ec2.rb

### CODE REVIEW

**Comment by jdevesa** [comment]
I realised that the patch does not solve the problem. I'll will update and reopen if I find the solution.

**Comment by jdevesa** [comment]
The docker image I am using to test it is [midonet/centos:centos6](https://registry.hub.docker.com/u/midonet/centos/tags/manage/) NOTE: **centos6** is the one that uses upstart. **centos7** uses systemd and it is a completely different animal.

**Comment by ekrupnik** [comment]
@jdevesa How long are you noticing that the connections are taking?

CC: https://github.com/test-kitchen/test-kitchen/pull/454

**Comment by jdevesa** [comment]
@ekrupnik problem is that the [test_ssh method](https://github.com/test-kitchen/test-kitchen/blob/v1.3.1/lib/kitchen/ssh.rb#L264) called by the [wait method](https://github.com/test-kitchen/test-kitchen/blob/v1.3.1/lib/kitchen/ssh.rb#L132) tests if the socket of the host port is open instead of test over the containers' ssh port (which is forwarded from the host port). Host port is immediately open, and it does not wait at all, whereas the ssh port of the container may take a while to be ready.

So instead of test if the socket is open, we need to do an actual ssh connection at 'wait_for_sshd' statement.

Does this explanation answer you question?

**Comment by fnichol** [comment]
Heads up for everyone reading that I've been re-working the SSH-related code to be a full fledged plugin just like Drivers and Provisioners called a Transport. You can see a nearly completed version of the [SSH Transport](https://github.com/fnichol/test-kitchen/blob/22738ce11350ea5223fe03c0ef2f922719c9d3c5/lib/kitchen/transport/ssh.rb) which will be included in the next release of Test Kitchen.

I'm hoping that this will properly resolve the race conditions when SSH boots and restarts. This involves a new `#wait_until_ready` method that Driver authors can use in their `#create` method, something like this:

```ruby
class MyDriver

  def create(state)
    # create my instance
    state[:hostname] = "my_hostname"
    # other details

    transport.connection(state).wait_until_ready
  end
end
```

This will do something much more similar to @jdevesa's implementation here, i.e. invoking a command over SSH before calling the connection ready.

**Comment by portertech** [comment]
@fnichol tell me what to do :)

**Comment by miketheman** [comment]
Ping @fnichol

**Comment by portertech** [comment]
@fnichol PING\n

**Pull request closed without merging**
