### PR TITLE
Allow using temp directory for Dockerfile on modern Docker

### PR DESCRIPTION
**Pull request by amontalban**
Docker 17.05 added an option to perform `docker build` with the Dockerfile piped through `stdin`, but being able to use local (or remote) build-context. Prior to docker 17.05, building an image with a Dockerfile from `stdin` did not send the build-context.

In our use case it allows us to run multiple builds inside a Jenkins pipeline parallel step, without this there was a race-condition where the Dockerfiles were copied to containers (By `kitchen-salt`) and sometimes the file was already gone making build to fail.

References:

moby/moby#27393
moby/moby#31236
docker/docker.github.io#3538

### CODE REVIEW

**Comment by coderanger** [comment]
I don't really understand the use case, we use a random-named tempfile for the actual Dockerfile already, so multiple, parallel builds should be fine.

**Comment by amontalban** [comment]
Hi @coderanger,

Thanks for the reply, I know that our use case might be super complex so let me explain the problem we are trying to solve here.

We have a Jenkins running a pipeline that runs tests for our SaltStack configuration, in this pipeline we use a parallel step that runs multiple `kitchen test` commands. Some of this commands uses Docker as driver and some use Vagrant.

The problem is that `kitchen-salt` creates a sandbox and prepares all the files needed to be transferred to the container or the VM (Which is all the files and directories), and since we have multiple process creating random short lived Dockerfiles in the current directory this generates a race condition when a copy process tries to copy a Dockerfile created by other process that at the time to copy the file it was already gone. The copy process of `kitchen-salt` is in [1].

I know that maybe it's not a common thing, so perhaps we have to have an option for this? What do you think?

Thanks!

[1] https://github.com/saltstack/kitchen-salt/blob/4d3f8c010c96c02e63095ff393cc14eb4710c6a9/lib/kitchen-salt/util.rb#L34

**Comment by coderanger** [comment]
That sounds like a bug in kitchen-salt, it should be following the same convention as the Chef drivers where the sandbox is an arbitrary temp dir and is not related to the folder `.kitchen.yml` is in. Not really sure how it would be related to the driver either way though, the container is created before the provisioner is run.

**Comment by jeffreycoe** [comment]
Closing this PR due to inactivity. Please submit a new PR if this feature is still needed. Thanks!

**Pull request closed without merging**
