### PR TITLE
Adding options driver_config to allow any docker arguments to be used

### PR DESCRIPTION
**Pull request by mwain**
I had a use case where i needed to set a static known IP to a container while testing.
This adds extra docker config to allow any docker arguments to be used

### CODE REVIEW

**Comment by coderanger** [comment]
This is probably config overkill, we should add a generic `docker_options` or something and leave it at that.

**Comment by mwain** [comment]
Maybe, but then would the other docker options get refactored down?

**Comment by coderanger** [comment]
It's easier to stop adding new options than to fix old ones, that would require a slower deprecation march.

**Comment by mwain** [comment]
@coderanger I have updated the PR to add a generic options options, which can be used like:
```
driver_config:
  options:
    - "--ip=172.10.0.10"
    - "--net=bridge"
```

**Comment by coderanger** [comment]
Sorry, I actually just implemented this yesterday :)

**Pull request closed without merging**
