### PR TITLE
Custom build path

### PR DESCRIPTION
**Pull request by guskovd**
In some cases, I want to collect a container from a specific folder.

For example, in my image folder:
```bash
Dockerfile entry.sh
```
And I only need these 2 files to compile the image. 

My commit allows you to execute the bash command:
```bash
docker build -f Dockerfile image
```

by adding in .kitchen.yml:
```yaml
build_path: 'image'
```

### CODE REVIEW

**Comment by coderanger** [comment]
Can you be more specific about the use case? Remember that this is _not_ a Docker image testing tool, it's a Chef cookbook testing tool (and Ansible, Salt, Puppet) that happens to use Docker as lightweight VM-ish things.

**Comment by guskovd** [comment]
I believe that this feature is really not enough. Any option can be thrown through build_options. And only the context is hardcoded in "."

**Comment by coderanger** [comment]
You can use a `.dockerignore` file as per normal, perhaps you should try that first?

**Comment by guskovd** [comment]
> You can use a `.dockerignore` file as per normal, perhaps you should try that first?

- I can build an image and launch it in docker hub
- I can build an image using rakefile
- I can put .kitchen.yml in a subfolder

Why not just accept pull request? It does not break anything, just allows you to replace the "." on something else

**Comment by coderanger** [comment]
As I said, testing the Docker image is _not_ what this driver is for. It's for testing CM scripts and happens to use Docker. As such, I don't offer the full power of Docker :) And as for not accepting PRs, this project is mostly in maintenance mode so a new feature must reach a fairly high bar of importance to justify adding it. Unless there is a strong reason to not use a normal `.dockerignore` file, I don't think this is required.

**Comment by jeffreycoe** [comment]
Closing this PR due to inactivity. Please submit a new PR if this feature is still needed. Thanks!

**Pull request closed without merging**
