### PR TITLE
Support custom environment variables.

### PR DESCRIPTION
**Pull request by troykinsella**

### CODE REVIEW

**Comment by coderanger** [comment]
Any reason to not do this on a the command line with the existing options?

**Comment by troykinsella** [comment]
If supplying many custom command line options, it can get cluttered. Environment variables are a nice category of options that can be factored into their own config element.

**Comment by coderanger** [comment]
Given the massive config sprawl we already have, and that fact that I'm planning to remove the dynamic build stuffs, you should use the existing `build_options` and/or `run_options`.

**Comment by troykinsella** [comment]
Alrighty. Thanks for looking!

**Pull request closed without merging**
