### PR TITLE
Support alpine platform

### PR DESCRIPTION
**Pull request by ahelal**
Hi,

First thank you for kitchen-docker, This PR adds support for Alpine linux as a platform.
I read the history of PR #190. I understand that chef does not yet support Alpine.
Here is a working [example](https://github.com/AutomationWithAnsible/ansible-usermanage/blob/master/.kitchen.yml) that works with Anisble provisioner and Serverspec verifier. 

Regards,

### CODE REVIEW

**Comment by ahelal** [comment]
Hi any feedback concerning possibility of accepting Alpine ?

**Comment by ahelal** [comment]
Guys i would really appreciate a feedback even a negative one.

**Comment by tristanmorgan** [comment]
+1
I tried it out and was wondering why did you pull the shadow package from the edge repo?

**Comment by ahelal** [comment]
@tristanmorgan I don't remember exactly, but I think it was related to `useradd` since it needs to add kitchen user.

**Comment by jeffreycoe** [comment]
Closing this PR due to inactivity and it looks to be a duplicate of #288.

**Pull request closed without merging**
