### PR TITLE
Set default hostname with Kitchen instance name

### PR DESCRIPTION
**Pull request by snahelou**
Hello

Implementation of https://github.com/portertech/kitchen-docker/issues/152 and https://github.com/portertech/kitchen-docker/issues/79

Regards

### CODE REVIEW

**Comment by coderanger** [comment]
What happens if you try to boot two containers with the same name on a single docker server? (eg. testing two cookbooks at once)

**Comment by snahelou** [comment]
I've try with and without this fix and result is the same. 

It seem that Kitchen create only 1 container ( 1 @IP / port ) when you declare 2 instances with the same name. 
```bash
$ tail .kitchen.yml 

suites:
  - name: default
    manifest: angie.pp
  - name : test-A
    manifest: angie.pp
  - name : test-A
    manifest: angie.pp

$ kitchen list
Instance                     Driver  Provisioner  Last Action
default-centos-66            Docker  PuppetApply  <Not Created>
default-centos-71            Docker  PuppetApply  <Not Created>
test-A-centos-66             Docker  PuppetApply  <Not Created>
test-A-centos-71             Docker  PuppetApply  <Not Created>
test-A-centos-66             Docker  PuppetApply  <Not Created>
test-A-centos-71             Docker  PuppetApply  <Not Created>

$ kitchen create test-A-centos-66
-----> Starting Kitchen (v1.3.1)
........
       Finished creating <test-A-centos-66> (0m2.57s).
-----> Kitchen is finished. (0m3.30s)

$ kitchen list
Instance                     Driver  Provisioner  Last Action
default-centos-66            Docker  PuppetApply  <Not Created>
default-centos-71            Docker  PuppetApply  <Not Created>
test-A-centos-66             Docker  PuppetApply  Created
test-A-centos-71             Docker  PuppetApply  <Not Created>
test-A-centos-66             Docker  PuppetApply  Created
test-A-centos-71             Docker  PuppetApply  <Not Created>

$ ps -ef | grep docker
root      3248   999  0 10:27 ?        00:00:00 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 32771 -container-ip 172.17.0.4 -container-port 22

```

But I don't understand the aim of declaring 2 instances with the same name. 

Regards.

**Comment by miry** [comment]
:+1:

**Comment by coderanger** [comment]
The issue wouldn't be with one `kitchen.yml`, but if you had two different configs using the same docker server at the same time.

**Comment by looztra** [comment]
of course this would not work because docker won't let your create 2 containers with the same name.

We could add a unique id based on the current directory for instance?

We need to generate a deterministic hostname so that we can write tests for each combination of the platform+suite combination based on the hostname.

**Comment by miry** [comment]
@looztra May be I am wrong but hostname and docker container name are different. By default hostname is equal docker container id. 
[Screen1](https://drive.google.com/file/d/0B6mIeMASod32VjhKclpHMGRYb0k/view?usp=sharing)
[Screen2](https://drive.google.com/file/d/0B6mIeMASod32QURQbjNXdFQ4UW8/view?usp=sharing)

**Comment by coderanger** [comment]
@miry The container name is what we actually want to set though, so you can know which containers map to which tests.

**Comment by looztra** [comment]
@miry is right, I mixed *name* and *hostname*.

So yes, docker can perfectly handle containers with the same hostname (like Vagrant and that's not a problem for the kitchen-vagrant driver).

@coderanger nope, what we want to set is the *hostname* because sometimes you want to customize tests data by relying on the hostname.

To sum up my pov, setting a default hostname according to a combination of the suite and platform name as proposed by @snahelou should not be a problem (that's exactly what the kitchen-vagrant driver does)

**Comment by miry** [comment]
Why I see this pr is good for me. Because in local machine I test via vagrant, but for circle ci I use docker. And i test that my  config has correct option that related on hostname. Do you have some suggestions how to to test it without this patch?

**Comment by cdelgehier** [comment]
:+1:

**Pull request closed without merging**
