### PR TITLE
Adding environment variables to docker run command via .kitchen.yml

### PR DESCRIPTION
**Pull request by dsklopp**
Adding driver_config option for loading environment variables in docker run command.  I'm not convinced it is the best place to put the configuration, so let me know if you want me to move things around.

### CODE REVIEW

**Comment by coderanger** [comment]
What is your use case? These wouldn't really be used during Chef testing and I'm not sure this is a good tool for testing containers in a more general fashion.

**Comment by dsklopp** [comment]
Docker frequently uses environment variables for runtime configuration.  I'm building docker images via Chef and packer, but I utilize test-kitchen for testing and prototyping.  Enabling environment variable support enables me to test how the container will run and orchestrated not only in test-kitchen, but in real environments.  Otherwise my prototype environment is distinct from staging, production or any non test-kitchen environment.

**Comment by coderanger** [comment]
The primary use case for this gem is testing Chef cookbooks, but this is probably unobtrusive enough to do. That said, Test Kitchen is not built to be a Docker image testing tool, so this is unlikely to be the only pitfall you'll hit.

**Comment by coderanger** [comment]
Notably this gem installs a bunch of stuff inside the container and assumes the container will behave like a little VM, which should not be how most containers are built. If you're looking for purely external testing, I would use Serverspec or InSpec directly in their remote execution modes.

**Comment by dsklopp** [comment]
Actually this opens a far more interesting topic that I have not seen addressed anywhere, and is beyond the scope of Chef (let alone test-kitchen).  I have struggled to answer this.  If you have any thoughts / suggestions on the matter I would love to hear it.

How do we repeatedly test and configure docker containers?  Most people generate Docker images via Dockerfiles, which are effectively BASH scripts.  I used to do this professionally 10+ years ago, and it was non-repeatable, very hard to test, highly dependent upon the starting state, and error prone due to naturally non idempotent steps.  Yes, yes, a Dockerfile is theoretically repeatable, but only if you start from the same starting state and the situation hasn't changed (aka, package updates breaking something?) since you last ran it.  Theoretically one will always have that docker image stored for all time thereafter, but the knowledge of how it was created may be impossible to effectively reproduce (someone manually tweaks the container and commits it as a new image).  The image is passed around between multiple developers, each one taking new commits.

In my experience, Docker images are less infrastructure as code and more "snapshots of what I googled".  I strongly prefer Chef cookbooks.  Though cookbooks undoubtedly add complexity to the unfamiliar, they build upon prior domain knowledge, repeatable steps, and testing frameworks.  For example, installing nginx the naive way (sudo apt-get -y install nginx) works, but with the Chef cookbook, it provides real, extensible code, built upon prior domain knowledge of the product.  This is in stark contrast to downloading the package, using sed to hard code some values someone read off of StackOverflow, and otherwise building upon zero domain knowledge outside of that.  In contrast, using the nginx cookbook, it was intelligently configured, and with just a few attribute tweaks, it can be highly customized to a good, maintainable, and testable installation.

This is a question I am personally struggling to answer in an adequate way.  If you have any thoughts on it, please let me know.

**Comment by coderanger** [comment]
The overall structure of Test Kitchen can definitely work for testing Docker images, but this gem is not for that and I don't want to try and add it given how different it would be from testing cookbooks (or similar, modules, playbooks, etc).

The way I would imagine it working would be a driver that is similar to this one but rather than doing a Dockerfile and a build, it just runs a given image as is. This would probably be paired with a custom verifier plugin that uses InSpec's docker execution mode so we don't have to install/configure SSH access. Totally in favor of someone writing that driver/verifier, it just isn't this one.

**Pull request closed without merging**
