### PR TITLE
Initial basic support for non-authenticating proxy

### PR DESCRIPTION
**Pull request by jcejohnson**

### CODE REVIEW

**Comment by portertech** [comment]
Perhaps we should instead expose a config option for environment variables?

**Comment by jcejohnson** [comment]
If you mean an option to use the workstation's environment variables, that won't work for my particular usecase (and potentially others who are subject to restrictive corporate policies). Corporate rules don't allow us to do local virtualization so my docker host is actually a remote VM which lives in a different network with a different proxy configuration.

**Comment by jeffreycoe** [comment]
The current release of this gem has support for environment variables and executing docker containers on a remote system. Closing this PR due to inactivity, but if this feature is still required, please submit a new PR with the latest release. Thanks.

**Comment by Xorima** [comment]
Regarding forwarding env vars in, all env vars which are prefixed `TK_` get forwarded in so `TK_HTTP_PROXY` would become `HTTP_PROXY` in the container.

**Pull request closed without merging**
