### PR TITLE
Retry if container rm reports fail

### PR DESCRIPTION
**Pull request by NathanZook**
Docker daemon can report that a container rm fails, even though it completes.  This...complicates the driver code.  In the meantime, have a retry!

Macintosh:wp_docker_deploy-cookbook nzook$ boot2docker version
Client version: v1.2.0
Git commit: a551732
Macintosh:wp_docker_deploy-cookbook nzook$ docker version
Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.3.1
Git commit (client): fa7b24f
OS/Arch (client): darwin/amd64
Server version: 1.2.0
Server API version: 1.14
Go version (server): go1.3.1
Git commit (server): fa7b24f

...

   Finished in 0.31451 seconds
   12 examples, 0 failures
   Finished verifying <default-ubuntu-1404> (0m2.22s).
...  (container inspection)
    >>>>>> ------Exception-------
    >>>>>> Class: Kitchen::ActionFailed
    >>>>>> Message: Failed to complete #destroy action: [Expected process to exit with [0], but received '1'
    ---- Begin output of docker -H tcp://192.168.59.103:2375 rm b383a4e3f8cfe8625297ff5fc18fbfb643bbc21eab51b11e1e94653776f7b028 ----
    STDOUT: 
    STDERR: Error response from daemon: Cannot destroy container b383a4e3f8cfe8625297ff5fc18fbfb643bbc21eab51b11e1e94653776f7b028: Driver aufs failed to remove root filesystem b383a4e3f8cfe8625297ff5fc18fbfb643bbc21eab51b11e1e94653776f7b028: rename /mnt/sda1/var/lib/docker/aufs/diff/b383a4e3f8cfe8625297ff5fc18fbfb643bbc21eab51b11e1e94653776f7b028 /mnt/sda1/var/lib/docker/aufs/diff/b383a4e3f8cfe8625297ff5fc18fbfb643bbc21eab51b11e1e94653776f7b028-removing: device or resource busy
    2014/09/16 11:45:36 Error: failed to remove one or more containers
    ---- End output of docker -H tcp://192.168.59.103:2375 rm b383a4e3f8cfe8625297ff5fc18fbfb643bbc21eab51b11e1e94653776f7b028 ----
    Ran docker -H tcp://192.168.59.103:2375 rm b383a4e3f8cfe8625297ff5fc18fbfb643bbc21eab51b11e1e94653776f7b028 returned 1]
    >>>>>> ----------------------
    >>>>>> Please see .kitchen/logs/kitchen.log for more details
    >>>>>> Also try running `kitchen diagnose --all` for configuration

Macintosh:wp_docker_deploy-cookbook nzook$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
Macintosh:wp_docker_deploy-cookbook nzook$ docker images
REPOSITORY                             TAG                 IMAGE ID            CREATED             VIRTUAL SIZE

### CODE REVIEW

**Comment by coderanger** [comment]
Oy, so I love this feature but I kind of want to find a way to make this work without checking for specific error messages. I will have to think on this for a bit.

**Comment by cpoole** [comment]
Why not a simple loop check? 
```
if initial command returns failure AND checked less than 3 times
     sleep 2
     if container is destroyed
          exit
     else
          increment and loop
```
this way blanket removal errors are covered and at most you wait an extra 6 seconds for deletion to fail

**Comment by NathanZook** [comment]
So, this was submitted 2 1/2 years ago.  At that time Docker was still quite immature.  The error check was extremely narrow because there are many potential reasons for the container destruction to fail, and I wanted to catch only the false-failing case.  Not knowing anything really about docker internals or direction, I expected that the real solution would involve changing the docker rm command.  Thus "in the mean time".

**Comment by cpoole** [comment]
I understand where you are coming from. 

I still see this error today though running on Docker 12.6 so my thought process is for an extra 6 seconds on the deletion step this could fix multiple removal errors. To me an extra 6 seconds waiting for a delete far outweighs the lost time due to a false negative in a cookbook test.

**Comment by NathanZook** [comment]
Yikes!  Well, I'm officially reentering the docker world tomorrow.  I'm not certain if my home system is beefy enough to really run stuff.  Do you have a reliable failing case?  At the point, it is probably best to open a new ticket, and reference this.  Please cc me on the ticket.

**Comment by cpoole** [comment]
Will do. 

Unfortunately I dont have a very reliable test case. I can generate the error when I'm really hammering our compute nodes, but only about 50% of the time will one of our many cookbooks fail during our roughly 2 hour validation... Basically it's a huge pain in the ass to replicate.

I'll see if I can dig deeper to find a more replicate-able failure env.

Personally I think this is an AUFS storage driver issue during periods of high container churn.

**Comment by NathanZook** [comment]
Yeah, that's why I did not post an example, either.  But I don't think it is necessarily about container churn.  I'm betting it is a straight-up race, and anything that causes a delay in the report of the shutdown could cause a failure report while the actual shutdown proceeds.

**Comment by cpoole** [comment]
Here's a kitchen error log from my end:
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #destroy action: [Expected process to exit with [0], but received '1'
---- Begin output of docker -H unix:///var/run/docker.sock rm 85cd71302acddb54d31d5000bdbf2f2343a8e9064539071a6e135c565022ab62 ----
STDOUT: 
STDERR: Error response from daemon: Driver aufs failed to remove root filesystem 85cd71302acddb54d31d5000bdbf2f2343a8e9064539071a6e135c565022ab62: rename /var/lib/docker/aufs/diff/ce5e8fd084a719042f559ccbdd639658c884e2c2a39c5d4cb5968e13714585ab /var/lib/docker/aufs/diff/ce5e8fd084a719042f559ccbdd639658c884e2c2a39c5d4cb5968e13714585ab-removing: device or resource busy
---- End output of docker -H unix:///var/run/docker.sock rm 85cd71302acddb54d31d5000bdbf2f2343a8e9064539071a6e135c565022ab62 ----
Ran docker -H unix:///var/run/docker.sock rm 85cd71302acddb54d31d5000bdbf2f2343a8e9064539071a6e135c565022ab62 returned 1] on jenkins-nginx-ubuntu-1604
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by jeffreycoe** [comment]
Closing PR due to inactivity. Please open a new PR if this issue still exists with the latest release. Thanks!

**Pull request closed without merging**
