### PR TITLE
Allow Multiple Platform Names for Windows

### PR DESCRIPTION
**Pull request by jeffreycoe**
Currently, only one platform name can be used for Windows as the platform name has to be exactly named "windows" as shown in the kitchen config below:

```
platforms:
  - name: windows
    driver_config:
      image: mcr.microsoft.com/windows/servercore:1607
      platform: windows
```

This update checks to see if the platform name includes the string "windows" instead (shown in the configuration below):

```
platforms:
  - name: windows-chef-12
    provisioner:
      product_name: chef
      product_version: 12.14.89
    driver_config:
      image: mcr.microsoft.com/windows/servercore:1607
      platform: windows
  - name: windows-chef-14
    provisioner:
      product_name: chef
      product_version: 14.7.17
    driver_config:
      image: mcr.microsoft.com/windows/servercore:1607
      platform: windows
  - name: windows-chef-latest
    provisioner:
      product_name: chef
    driver_config:
      image: mcr.microsoft.com/windows/servercore:1607
      platform: windows
```

Also updated test kitchen config with correct opensuse image name for the CI test to pass.

### CODE REVIEW

**Comment by jeffreycoe** [comment]
Hi @stuartpreston - Before we release a new version of this gem, would you be able to review and merge this PR if you approve? Thanks!

**Comment by lmayorga1980** [comment]
@stuartpreston how soon the new release/gem will be created?

**Comment by stuartpreston** [comment]
@lmayorga1980 Whilst I have commit rights on this repo (by virtue of being a maintainer for kitchen-azurerm) I do not have release rights on the project to release the gem. Hopefully merging this change will fix the outstanding build issues and then I'll ping the team again to see if it can be released with the experimental Windows fixes. Thanks for the patience.

**Comment by lmayorga1980** [comment]
@stuartpreston build looks green now :+1:

**Comment by jeffreycoe** [comment]
@stuartpreston Thanks for reviewing and merging. Please reach out if you need anything to help get the new gem released. 👍

**Pull request merged**
