### PR TITLE
refactor!: Run chefstlye over the codebase

### PR DESCRIPTION
**Pull request by damacus**
- Run chefstyle
- Move development dependencies into the Gemfile
- Remove tailor and cane which are no longer maintained

# Description

Please describe what this change achieves

## Issues Resolved

List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant

## Type of Change

- Major

## Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [ ] Commit message includes a [Conventional Commit Message](https://www.conventionalcommits.org/en/v1.0.0)

### CODE REVIEW

**Comment by damacus** [comment]
@test-kitchen/maintainers here's the promised move to ChefStyle. I'm not sure why this wasn't using ChefStyle before. 

Anyone but @xorima can review this one 😆 😆

**Review by xorima — APPROVED** [review]

**Comment by xorima** [comment]
@damacus i didn't read the above and approved it 😂

**Comment by damacus** [comment]
@xorima what do you mean? 

The kitchen tests currently run on the same platform set as the kitchen.yml 

default and capabilities are failing due to including busser-serverspec. This needs to be fixed in a subsequent PR. 

Given the size of the rubocopping on this branch I'm inclined to make non-related changes in another PR

**Comment by xorima** [comment]
@damacus makes total sense. 
Tbh I did a spot check of the windows failure and it was failing around platform not defined etc. 
moving this to a different pr to fix is the better approach I agree. (I've looked at a couple others now and they actually run something so it was just my luck during spot check)

**Pull request merged**
