### PR TITLE
Fix rake violations

### PR DESCRIPTION
**Pull request by wtanaka**
Running `rake` produced warnings.  This change fixes some of them.

### CODE REVIEW

**Comment by coderanger** [comment]
@portertech I defer to your judgement on style stuffs. AFAICT this shouldn't break anything :)

**Comment by wtanaka** [comment]
Is running `rake` not a normal thing to do?  I haven't really used Ruby before.

**Comment by alexanderadam** [comment]
I would love to see these things merged after fixing the conflicts of course. :wink:

**Comment by coderanger** [comment]
Closing this out pending a larger revamp of style checks.

**Pull request closed without merging**
